package com.devsda.platform.shepherd.constants;

public enum ResourceName {

    EXECUTE_WORKFLOW,
    KILL_EXECUTION,
    RESUME_EXECUTION,
    RESTART_EXECUTION,
    REGISTER_CLIENT,
    REGISTER_ENDPOINT,
    UPDATE_ENDPOINT,
    RETRIEVE_REGISTERED_CLIENTS,
    RETRIEVE_REGISTERED_ENDPOINTS,
    RETRIEVE_ENDPOINT,
    GET_GRAPH
}
